### ISSUE TITLE
Building a Windows image

### ISSUE THREAD

**Issue by srufle** [chef/bento#343]
Tried to run 
`bundle exec veewee vbox build windows-2012r2-standard`

It ran well untill I saw this at the end
```
C:\Users\vagrant>msiexec /qb /i "C:\Users\vagrant\AppData\Local\Temp\chef-client-latest.msi" 
/var/lib/gems/1.9.1/gems/winrm-1.1.3/lib/winrm/http/transport.rb:48:in 'send_request': Bad HTTP response returned from server (500). (WinRM::WinRMHTTPTransportError)
        from /var/lib/gems/1.9.1/gems/winrm-1.1.3/lib/winrm/winrm_service.rb:368:in 'send_message'
        from /var/lib/gems/1.9.1/gems/winrm-1.1.3/lib/winrm/winrm_service.rb:155:in 'get_command_output'
```
Solved the issue by commenting out the last msiexec line in all install-chef.bat files I could find
```
-msiexec /qb /i "%LOCAL_DESTINATION_MSI_PATH%"
+@REM msiexec /qb /i "%LOCAL_DESTINATION_MSI_PATH%"
``` 
earlier in the same file it looked to already be installed
```
C:\Users\vagrant>cscript /nologo C:\Users\vagrant\AppData\Local\Temp\wget.vbs /url:https://www.opscode.com/chef/install.msi /path:"C:\Users\vagrant\AppData\Local\Temp\chef-client-latest.msi" 
```

**Comment by juliandunn** [comment]
Yeah... I should actually get rid of all those veewee definitions as they're unmaintained.

**Comment by juliandunn** [comment]
In #358, we deprecated the veewee definitions. So this issue is no longer applicable.
