### ISSUE TITLE
FreeBSD 10.3 lacks localhost entry

### ISSUE THREAD

**Issue by madelaney** [chef/bento#755]
The file `/etc/hosts` has an entry for 127.0.0.1 but has the hostname set to `updates.puppetlabs.com` but not one for localhost.

For some application (i.e. java) need, need an entry for localhost. For example:
```
SEVERE: StandardServer.await: create[localhost:8015]:
java.net.BindException: Can't assign requested address (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:375)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at org.apache.catalina.core.StandardServer.await(StandardServer.java:420)
        at org.apache.catalina.startup.Catalina.await(Catalina.java:717)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:663)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:351)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:485)
```

**Comment by amontalban** [comment]
Hi @madelaney 

I think that you have a custom build or something, this is my `/etc/hosts` file on stock image:

```
root@freebsd-10:/var/cache # cat /etc/hosts
# $FreeBSD: releng/10.3/etc/hosts 109997 2003-01-28 21:29:23Z dbaker $
#
# Host Database
#
# This file should contain the addresses and aliases for local hosts that
# share this file.  Replace 'my.domain' below with the domainname of your
# machine.
#
# In the presence of the domain name service or NIS, this file may
# not be consulted at all; see /etc/nsswitch.conf for the resolution order.
#
#
::1                     localhost localhost.my.domain
127.0.0.1               localhost localhost.my.domain
#
# Imaginary network.
#10.0.0.2               myname.my.domain myname
#10.0.0.3               myfriend.my.domain myfriend
#
# According to RFC 1918, you can use the following IP networks for
# private nets which will never be connected to the Internet:
#
#       10.0.0.0        -   10.255.255.255
#       172.16.0.0      -   172.31.255.255
#       192.168.0.0     -   192.168.255.255
#
# In case you want to be able to connect to the Internet, you need
# real official assigned numbers.  Do not try to invent your own network
# numbers but instead get one from your network provider (if any) or
# from your regional registry (ARIN, APNIC, LACNIC, RIPE NCC, or AfriNIC.)
#
```

**Comment by madelaney** [comment]
@amontalban, my apologies. After further testing, this appears to be caused by beaker (or something there within). I'll close this out.

**Comment by cheeseplus** [comment]
I was going to ask based on the FQDN being suspect but glad you got it worked out!
