### ISSUE TITLE
Boxes not compatible with older HyperV

### ISSUE THREAD

**Issue by ilovemysillybanana** [chef/bento#997]
## OS Information
```
PS C:\Users\jose.tobar\cookbooks\sonarqube> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
```

Windows 2016 

## Vagrant Driver
```
PS C:\Users\jose.tobar\cookbooks\sonarqube> vagrant -v
Vagrant 2.0.2
```

## ChefDK Version
```
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```

## Output
```
PS C:\Users\jose.tobar\cookbooks\sonarqube> kitchen create -l debug
-----> Starting Kitchen (v1.19.2)
D      [Vagrant command] BEGIN (vagrant --version)
D      [Vagrant command] END (0m0.00s)
D      Berksfile found at C:/Users/jose.tobar/cookbooks/sonarqube/Berksfile, loading Berkshelf
D      Berkshelf 6.3.1 library loaded
-----> Creating <sq-server-bento-ubuntu-1604>...
D      <sq-server-bento-ubuntu-1604> is synchronizing on Kitchen::Driver::Vagrant#create
D      <sq-server-bento-ubuntu-1604> is messaging Kitchen::Driver::Vagrant#create
D      Creating Vagrantfile for <sq-server-bento-ubuntu-1604> (C:/Users/jose.tobar/cookbooks/sonarqube/.kitchen/kitchen-vagrant/sq-server-bento-ubuntu-1604/Vagrantfile)
D      ------------
D      Vagrant.configure("2") do |c|
D        c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
D        c.vm.box = "bento/ubuntu-16.04"
D        c.vm.hostname = "sq-server-bento-ubuntu-1604.vagrantup.com"
D        c.vm.network(:public_network, {:bridge=>"LAN"})
D        c.vm.synced_folder ".", "/vagrant", disabled: true
D        c.vm.provider :hyperv do |p|
D        end
D      end
D      ------------
D      [Vagrant command] BEGIN (vagrant up --no-provision --provider hyperv)
       Bringing machine 'default' up with 'hyperv' provider...
       ==> default: Verifying Hyper-V is enabled...
       ==> default: Importing a Hyper-V instance
       Looking for switch with name: LAN
       Found switch: LAN
           default: Cloning virtual hard drive...
           default: Creating and registering the VM...
       An error occurred while executing a PowerShell script. This error
       is shown below. Please read the error message and see if this is
       a configuration error with your system. If it is not, then please
       report a bug.

       Script: import_vm_vmcx.ps1
       Error:

       Hyper-V\Compare-VM : Failed to import a virtual machine.
       At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-2.0.2\plugins\providers\hyperv\scripts\import_vm_vmcx.ps1:33 char:14
       + $vmConfig = (Hyper-V\Compare-VM -Copy -GenerateNewID @VmProperties)
       +              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           + CategoryInfo          : NotSpecified: (:) [Compare-VM], VirtualizationException
           + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.CompareVM

D      [Vagrant command] END (0m0.00s)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider hyperv ----
STDOUT: Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
Looking for switch with name: LAN
Found switch: LAN
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
STDERR: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Hyper-V\Compare-VM : Failed to import a virtual machine.
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-2.0.2\plugins\providers\hyperv\scripts\import_vm_vmcx.ps1:33 char:14
+ $vmConfig = (Hyper-V\Compare-VM -Copy -GenerateNewID @VmProperties)
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Compare-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.CompareVM
---- End output of vagrant up --no-provision --provider hyperv ----
Ran vagrant up --no-provision --provider hyperv returned 1] on sq-server-bento-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider hyperv ----
STDOUT: Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
Looking for switch with name: LAN
Found switch: LAN
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
STDERR: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Hyper-V\Compare-VM : Failed to import a virtual machine.
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-2.0.2\plugins\providers\hyperv\scripts\import_vm_vmcx.ps1:33 char:14
+ $vmConfig = (Hyper-V\Compare-VM -Copy -GenerateNewID @VmProperties)
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Compare-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.CompareVM
---- End output of vagrant up --no-provision --provider hyperv ----
Ran vagrant up --no-provision --provider hyperv returned 1] on sq-server-bento-ubuntu-1604
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:183:in `report_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:174:in `run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command/action.rb:36:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command/action.rb:34:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:52:in `perform'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:13:in `block in <top (required)>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:13:in `<top (required)>'
D      C:/opscode/chefdk/bin/kitchen:267:in `load'
D      C:/opscode/chefdk/bin/kitchen:267:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider hyperv ----
STDOUT: Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
Looking for switch with name: LAN
Found switch: LAN
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
STDERR: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Hyper-V\Compare-VM : Failed to import a virtual machine.
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-2.0.2\plugins\providers\hyperv\scripts\import_vm_vmcx.ps1:33 char:14
+ $vmConfig = (Hyper-V\Compare-VM -Copy -GenerateNewID @VmProperties)
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Compare-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.CompareVM
---- End output of vagrant up --no-provision --provider hyperv ----
Ran vagrant up --no-provision --provider hyperv returned 1] on sq-server-bento-ubuntu-1604
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/shell_out.rb:71:in `rescue in run_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/shell_out.rb:59:in `run_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:435:in `run_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:382:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:466:in `run_vagrant_up'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:107:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:469:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:469:in `block in perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:533:in `block in synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:531:in `synchronize'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:531:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:498:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:497:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:469:in `perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:379:in `create_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:368:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:124:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider hyperv ----
STDOUT: Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
Looking for switch with name: LAN
Found switch: LAN
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
STDERR: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Hyper-V\Compare-VM : Failed to import a virtual machine.
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-2.0.2\plugins\providers\hyperv\scripts\import_vm_vmcx.ps1:33 char:14
+ $vmConfig = (Hyper-V\Compare-VM -Copy -GenerateNewID @VmProperties)
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Compare-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.CompareVM
---- End output of vagrant up --no-provision --provider hyperv ----
Ran vagrant up --no-provision --provider hyperv returned 1]
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/shell_out.rb:71:in `rescue in run_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/shell_out.rb:59:in `run_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:435:in `run_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:382:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:466:in `run_vagrant_up'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:107:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:469:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:469:in `block in perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:533:in `block in synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:531:in `synchronize'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:531:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:498:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:497:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:469:in `perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:379:in `create_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:368:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:124:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

I'm posting here because I believe the issue is with something to do with bento as not all other boxes exhibit this issue. For instance switching from bento/ubuntu1604 to generic/1604 resolved the issue for me. 

I'm referencing this issue because other users are experiencing it as well but with other boxes as well, I'm guessing something must be different during the creation of the image? Since it affects some boxes but not all.
https://github.com/hashicorp/vagrant/issues/9317

**Comment by cheeseplus** [comment]
Like I said in the other thread, this is a Vagrant code blowing up - regardless of whether there is a related box issue we can do NOTHING about that piece of code that is blowing up.

**Comment by ilovemysillybanana** [comment]
Oh, I'm sorry. I misunderstood. In that case we can just close this issue then.

**Comment by cheeseplus** [comment]
I'm happy to re-open or keep this open _if_ we can narrow this down to what specifically about the boxes is different enough to cause the upstream script to fail. Even if we do fix that, Vagrant will need to account for both conditions (or at least error better). The problem being since I don't know how those generic boxes are made I can't reason about what might be different in bento aside from guesses, the Generation 1 vs 2 being the only thing I have off the top of my head.

In the meantime I will try to get hands on a 2016 machine/vm because clearly something about earlier Hyper-V (prior to 10.0.16299) is unhappy with bento boxes.

**Comment by ilovemysillybanana** [comment]
I just found that centos makes hyper v vagrant boxes. It might be worth us taking a look at how they create their boxes since this one didn't have this problem:

https://vagrantcloud.com/centos/boxes/7/versions/1801.02/providers/hyperv.box

I am able to find the source for the 'generic' vms or who makes them unfortunately.

**Comment by cheeseplus** [comment]
Unfortunately I'm not seeing a repo that I can look at for these centos boxes either so it's the same problem as with the `generic` boxes.

**Comment by cheeseplus** [comment]
Closing this one as Vagrant has improved a bunch and this is still searchable for wanderers by.
